max_width = 80
fn_args_layout = "Tall"
format_strings = true
imports_layout = "HorizontalVertical"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
wrap_comments = true
use_field_init_shorthand = true
unstable_features = true
reorder_impl_items = true
normalize_comments = true
merge_derives = false
match_block_trailing_comma = true
force_multiline_blocks = true
condense_wildcard_suffixes = true
comment_width = 60
error_on_line_overflow = true
error_on_unformatted = true